## Importing PyTorch

In [1]:
import torch
torch.__version__

'2.13.0+cpu'

---
## Creating Tensors

In [2]:
# Creating Scalar
scalar = torch.tensor(7)
print(f"{scalar}")
print(f"Number of Dimensions of scalar is: {scalar.ndim}")
print(f"The number inside the tensor is: {scalar.item()}")

7
Number of Dimensions of scalar is: 0
The number inside the tensor is: 7


In [3]:
# Creating vector
vector = torch.tensor([7, 7])
print(f"{vector}")
print(f"Number of Dimenstion of vector is: {vector.ndim}")
print(f"The Shape of vector is: {vector.shape}")

tensor([7, 7])
Number of Dimenstion of vector is: 1
The Shape of vector is: torch.Size([2])


In [4]:
# Creating Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(f"{matrix}")
print(f"Number of Dimenstion of matrix is: {matrix.ndim}")
print(f"The Shape of matrix is: {matrix.shape}")

tensor([[ 7,  8],
        [ 9, 10]])
Number of Dimenstion of matrix is: 2
The Shape of matrix is: torch.Size([2, 2])


In [5]:
# Creating Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(f"{tensor}")
print(f"Number of Dimenstion of tensor is: {tensor.ndim}")
print(f"The Shape of tensor is: {tensor.shape}")

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
Number of Dimenstion of tensor is: 3
The Shape of tensor is: torch.Size([1, 3, 3])


---

## Creating Random Tensors

In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6669, 0.9669, 0.7153, 0.2995],
         [0.2765, 0.5235, 0.7580, 0.7961],
         [0.9122, 0.3079, 0.4173, 0.8663]]),
 torch.float32)

In [7]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensors = torch.rand(size=(224, 224, 224))
random_image_size_tensors.shape, random_image_size_tensors.ndim

(torch.Size([224, 224, 224]), 3)

---
## Zeros and ones

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

---
## Creating a range and tensors like

In [10]:
# Create a range tensor
zero_to_ten = torch.arange(0 , 11, 1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

---
# Tensor Datatypes

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float32, # The default type is float32
                               device= None,         # The default type is CPU or Cuda
                               requires_grad=False   # if True, operations performed on the tensor are recorded
                               )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

---
## Getting information from tensors

In [13]:
# Create a tensor
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.6409, 0.7168, 0.1698, 0.9444],
        [0.9123, 0.7163, 0.0496, 0.8942],
        [0.1752, 0.3855, 0.1857, 0.4716]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


---
## Manipulating tensors (tensor operations)

In [14]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Adding
print(f"Adding: {tensor + 10}")
print("=="*30)

# Multiply
print(f"Multiply: {tensor * 10}")
print("=="*30)

# Element-wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

Adding: tensor([11, 12, 13])
Multiply: tensor([10, 20, 30])
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [15]:
# Matrix Mulitplication - Dot Product
print(f"Dot Product: {tensor @ tensor}")

#================================================
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

print(f"Matrix Multiplication:")
print(tensor_A @ tensor_B.T)

Dot Product: 14
Matrix Multiplication:
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [16]:
# Transpose 
"""
tensor.transpose(dim0, dim1) - tensor.T
"""
tensor_B.transpose(0, 1)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

---
## Aggregation

In [17]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # mean function works only with float data type
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [19]:
# Positional min/max

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


---
## Change tensor datatype

In [20]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [21]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [22]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

---
## Reshaping, stacking, squeezing and unsqueezing

In [23]:
# Reshape the tensor
x = torch.arange(1., 8.)
x_reshaped = x.reshape(1, 7)


print(f"x: {x}, x.shape: {x.shape}")
print("==" * 30)
print(f"x reshaped: {x_reshaped}, x_reshaped.shape: {x_reshaped.shape}")

x: tensor([1., 2., 3., 4., 5., 6., 7.]), x.shape: torch.Size([7])
x reshaped: tensor([[1., 2., 3., 4., 5., 6., 7.]]), x_reshaped.shape: torch.Size([1, 7])


In [24]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
print(f"z: {z}, z.shape: {z.shape}")
print("=="*30)

# Changing z changes x
z[:, 0] = 5
print(z, x)

z: tensor([[1., 2., 3., 4., 5., 6., 7.]]), z.shape: torch.Size([1, 7])
tensor([[5., 2., 3., 4., 5., 6., 7.]]) tensor([5., 2., 3., 4., 5., 6., 7.])


In [25]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [26]:
# squeeze the tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [27]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [28]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


---
## Indexing

In [29]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [30]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [31]:
print(f"Get all values of 0th dimension and the 0 index of 1st dimension: {x[:, 0]}")
print(f"Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension: {x[:, :, 1]}")
print(f"Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimensions: {x[:, 1, 1]}")

Get all values of 0th dimension and the 0 index of 1st dimension: tensor([[1, 2, 3]])
Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension: tensor([[2, 5, 8]])
Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimensions: tensor([5])


---
## PyTorch tensors & NumPy

In [32]:
import numpy as np

# Numpy Array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [33]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

---
## Reproducibility 

In [34]:
# Create two random tensors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

---
## Running tensors on GPUs

In [35]:
# Check for GPU
torch.cuda.is_available()

False

In [36]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [37]:
# Count number of devices for GPUs
torch.cuda.device_count()

0

In [38]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

"""tensor([1, 2, 3], device='cuda:0')"""
# This must be the output if you have a GPU

tensor([1, 2, 3]) cpu


"tensor([1, 2, 3], device='cuda:0')"

In [39]:
# copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

#### - There is a lot of functions and properties that is the same of Numpy functions
#### - If you want to use a GPU. Go into a google colab